name: Auto Vote

on:
  schedule:
    - cron: "*/31 * * * *"

  workflow_dispatch:

jobs:
  vote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Vote Bot
        run: node vote.js
